name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"    # every day at midnight
  workflow_dispatch:

# ──────────────── Grant write access for repo contents ────────────────
permissions:
  contents: write       # Otherwise `GITHUB_TOKEN` is read-only by default :contentReference[oaicite:0]{index=0}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # ensure full history for branch operations

      - name: Generate snake animation SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rofljen
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: List generated files
        run: |
          echo "Contents of dist directory:"
          ls -R dist

      - name: Deploy SVG to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # explicitly pass the token :contentReference[oaicite:1]{index=1}
          branch: output                       # where to deploy
          folder: dist                         # what folder to push
