name: Build & Deploy Profile SVGs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rofljen
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Generate Achievements Badge
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_only: |
            polyglot, stargazer, sponsor, deployer, member,
            maintainer, developer, scripter, packager,
            explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - name: List dist directory
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          folder: dist
